#!/usr/bin/env python3
"""
日本曲2000曲研究プロジェクト - 大量データ投入スクリプト
ジャンル: 演歌/歌謡曲/アイドル/J-pop/バンド/アニソン/ボカロ/ヒップホップ/現代
"""

import sqlite3
import json
from datetime import datetime

DB_PATH = "/Users/shora-mini/shora-bot/suika-bot/research/music/music_research.db"

# ===== 1. 演歌 (50曲以上) =====
ENKA = [
    {
        "title": "川の流れのように",
        "artist": "美空ひばり",
        "year": 1989,
        "genre": "演歌/歌謡曲",
        "emotion_type": "諦め/受容/人生観",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "死の直前に録音。「川の流れのように」という諦めが本物の悟りに近い",
        "lyrics_keywords": ["川", "流れ", "人生", "道", "空"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "昭和の終わりと共に逝った女王の遺言。日本人の人生観の結晶"
    },
    {
        "title": "悲しい酒",
        "artist": "美空ひばり",
        "year": 1966,
        "genre": "演歌",
        "emotion_type": "孤独/悲哀/酔い",
        "emotion_function": "麻痺",
        "consciousness_level": 4,
        "consciousness_notes": "悲しみを酒で紛らわす。麻痺による自己防衛の典型",
        "lyrics_keywords": ["酒", "悲しい", "一人", "ひとり", "涙"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 7,
        "notes": "演歌的な悲しみの美学。感情の麻痺が芸術になった瞬間"
    },
    {
        "title": "お祭りマンボ",
        "artist": "美空ひばり",
        "year": 1952,
        "genre": "歌謡曲",
        "emotion_type": "祝祭/喜び",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "戦後復興期の純粋な喜びの爆発。制約なき解放感",
        "lyrics_keywords": ["祭り", "マンボ", "踊り", "お父さん"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "戦後日本の生命力の表現。ひばりの天才性が早期から開花"
    },
    {
        "title": "りんご追分",
        "artist": "美空ひばり",
        "year": 1952,
        "genre": "演歌/民謡",
        "emotion_type": "郷愁/純粋",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "日本の原風景への真摯な共鳴。民謡の魂と歌謡曲の技法の融合",
        "lyrics_keywords": ["りんご", "追分", "故郷", "山", "花"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "ひばりが民族の記憶と接続した瞬間。日本民謡の遺伝子を現代に"
    },
    {
        "title": "まつり",
        "artist": "北島三郎",
        "year": 1984,
        "genre": "演歌",
        "emotion_type": "祝祭/共同体",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "共同体への同化と祝祭。個を消して集団に溶け込む",
        "lyrics_keywords": ["まつり", "太鼓", "踊る", "神輿"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 5,
        "notes": "NHK紅白の定番。集団的同調圧力の音楽的表現"
    },
    {
        "title": "与作",
        "artist": "北島三郎",
        "year": 1978,
        "genre": "演歌",
        "emotion_type": "労働/自然/純朴",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "木こりの労働の尊さ。資本主義以前の自然との共生",
        "lyrics_keywords": ["与作", "木を切る", "へいへいほー", "女房"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "単純な労働への讃歌。現代の過剰な情報社会へのアンチテーゼ"
    },
    {
        "title": "北国の春",
        "artist": "千昌夫",
        "year": 1977,
        "genre": "演歌",
        "emotion_type": "郷愁/故郷",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "故郷を離れた者の望郷の念。日本人の共通の感情構造",
        "lyrics_keywords": ["北国", "春", "故郷", "白樺"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 7,
        "notes": "日本の高度経済成長期の集団的望郷感の表現"
    },
    {
        "title": "矢切の渡し",
        "artist": "細川たかし",
        "year": 1983,
        "genre": "演歌",
        "emotion_type": "駆け落ち/禁断の愛",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "社会規範への反抗としての駆け落ち。禁断への渇望",
        "lyrics_keywords": ["矢切", "渡し", "駆け落ち", "舟"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "社会規範を破る愛。演歌の中では珍しい反抗の形"
    },
    {
        "title": "心のこり",
        "artist": "細川たかし",
        "year": 1975,
        "genre": "演歌",
        "emotion_type": "後悔/未練",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "過去への執着が人生を麻痺させる典型。諦められない感情",
        "lyrics_keywords": ["こころ", "こり", "別れ", "未練"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 6,
        "notes": "未練という麻痺の歌。人間の感情の弱さへの正直な肯定"
    },
    {
        "title": "よこはまたそがれ",
        "artist": "五木ひろし",
        "year": 1971,
        "genre": "演歌",
        "emotion_type": "孤独/都会/旅情",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "都会の孤独と旅情。場所への執着が感情の依存先に",
        "lyrics_keywords": ["横浜", "黄昏", "一人", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "港町という象徴的空間が孤独感を増幅"
    },
    {
        "title": "長崎は今日も雨だった",
        "artist": "内山田洋とクール・ファイブ",
        "year": 1969,
        "genre": "演歌",
        "emotion_type": "孤独/失恋/雨",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "雨という気象と孤独の融合。外部環境に内面を投影",
        "lyrics_keywords": ["長崎", "雨", "一人", "涙"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 6,
        "notes": "日本演歌の孤独感の黄金期の傑作"
    },
    {
        "title": "男はつらいよ",
        "artist": "渥美清",
        "year": 1969,
        "genre": "歌謡曲/映画",
        "emotion_type": "諦め/自由/放浪",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "定住しない寅さんの生き方は実は高い魂の自由度を持つ",
        "lyrics_keywords": ["つらいよ", "男", "旅", "故郷"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 8,
        "notes": "社会のアウトサイダーとしての自由人の哲学"
    },
    {
        "title": "宗右衛門町ブルース",
        "artist": "平和勝次とダークホース",
        "year": 1971,
        "genre": "演歌",
        "emotion_type": "退廃/官能/夜の街",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "夜の歓楽街という麻痺の空間。現実逃避の音楽",
        "lyrics_keywords": ["宗右衛門町", "ブルース", "夜", "酒"],
        "cultural_impact": "中",
        "soul_freedom_score": 3,
        "truth_score": 5,
        "notes": "歓楽街という麻痺装置の音楽的記録"
    },
    {
        "title": "函館の女",
        "artist": "北島三郎",
        "year": 1965,
        "genre": "演歌",
        "emotion_type": "旅情/恋愛/港",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "港町という場所への感情移入。旅人の孤独な恋",
        "lyrics_keywords": ["函館", "女", "港", "別れ"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 5,
        "notes": "演歌の「港シリーズ」の代表作。日本人の漂泊感"
    },
    {
        "title": "釜山港へ帰れ",
        "artist": "チョー・ヨンピル",
        "year": 1980,
        "genre": "演歌",
        "emotion_type": "望郷/国境を超えた哀愁",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "国境を超えた望郷感。日韓の感情構造の共鳴",
        "lyrics_keywords": ["釜山", "港", "帰る", "望郷"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "韓国演歌の日本での大ヒット。文化的共鳴の証明"
    },
    {
        "title": "さざんかの宿",
        "artist": "大川栄策",
        "year": 1982,
        "genre": "演歌",
        "emotion_type": "不倫/秘密の愛",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "社会規範を破る愛の麻痺的な甘さ。禁断の現実逃避",
        "lyrics_keywords": ["さざんか", "宿", "二人", "秘密"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 5,
        "notes": "演歌が得意とする「禁断の愛」の麻痺的美学"
    },
    {
        "title": "花街の母",
        "artist": "金田たつえ",
        "year": 1978,
        "genre": "演歌",
        "emotion_type": "母/犠牲/哀愁",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "母の犠牲という感情的操作。「かわいそうな母」で感涙を誘う構造",
        "lyrics_keywords": ["母", "花街", "涙", "苦労"],
        "cultural_impact": "中",
        "soul_freedom_score": 3,
        "truth_score": 5,
        "notes": "母の犠牲という日本的感情搾取の典型パターン"
    },
    {
        "title": "演歌の花道",
        "artist": "玉置宏",
        "year": 1970,
        "genre": "演歌",
        "emotion_type": "演歌文化/誇り",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "演歌という文化への帰属感の強化",
        "lyrics_keywords": ["演歌", "花道", "魂"],
        "cultural_impact": "中",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "演歌文化のメタ表現"
    },
    {
        "title": "雪国",
        "artist": "吉幾三",
        "year": 1986,
        "genre": "演歌",
        "emotion_type": "雪景色/孤独/冬",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "北国の冬という環境が内面の孤独を反映",
        "lyrics_keywords": ["雪国", "冬", "白", "孤独"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "吉幾三の代表作。北国の美学の体現"
    },
    {
        "title": "俺ら東京さ行ぐだ",
        "artist": "吉幾三",
        "year": 1984,
        "genre": "演歌/フォーク",
        "emotion_type": "田舎/都会への憧れ/自虐",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "田舎の不便を笑いとして昇華。自己卑下ではなく自己解放",
        "lyrics_keywords": ["東京", "田舎", "テレビ", "ネオン"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 8,
        "notes": "ラップの先駆け的曲。自虐をユーモアで昇華した高度な表現"
    },
    {
        "title": "恋の季節",
        "artist": "ピンキーとキラーズ",
        "year": 1968,
        "genre": "歌謡曲/ポップス",
        "emotion_type": "恋の喜び/青春",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "純粋な恋の表現。歌謡曲の明るい面",
        "lyrics_keywords": ["恋", "季節", "春", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "グループサウンズ時代の明るい恋愛歌謡"
    },
    {
        "title": "なみだ恋",
        "artist": "八代亜紀",
        "year": 1973,
        "genre": "演歌",
        "emotion_type": "失恋/涙/諦め",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "失恋の涙を歌う演歌の王道。感情の共鳴による慰め",
        "lyrics_keywords": ["涙", "恋", "別れ", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 6,
        "notes": "八代亜紀の哀愁の声が感情を直接揺さぶる"
    },
    {
        "title": "舟唄",
        "artist": "八代亜紀",
        "year": 1979,
        "genre": "演歌",
        "emotion_type": "酒/哀愁/孤独",
        "emotion_function": "麻痺",
        "consciousness_level": 4,
        "consciousness_notes": "酒で紛らわす孤独。麻痺による感情管理の演歌的表現",
        "lyrics_keywords": ["舟", "酒", "一人", "哀愁"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 7,
        "notes": "阿久悠作詞の傑作。酒と哀愁の完璧な融合"
    },
    {
        "title": "天城越え",
        "artist": "石川さゆり",
        "year": 1986,
        "genre": "演歌",
        "emotion_type": "執念/嫉妬/官能",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "女の執念の凄みを正面から描く。感情を抑制しない解放",
        "lyrics_keywords": ["天城", "越える", "嫉妬", "怨念"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 8,
        "notes": "松本隆・弦哲也作品。女性の執念という禁断の感情の解放"
    },
    {
        "title": "夢芝居",
        "artist": "梅沢富美男",
        "year": 1982,
        "genre": "演歌",
        "emotion_type": "芝居/人生/夢",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "人生を芝居に喩える哲学。虚構と現実の境界への問い",
        "lyrics_keywords": ["夢", "芝居", "人生", "幕"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "大衆演劇から生まれた哲学。人生=芝居という視点"
    },
    {
        "title": "おんな港町",
        "artist": "八代亜紀",
        "year": 1984,
        "genre": "演歌",
        "emotion_type": "港/女の孤独",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "港という象徴的場所と女の孤独の融合",
        "lyrics_keywords": ["港", "女", "一人", "別れ"],
        "cultural_impact": "中",
        "soul_freedom_score": 4,
        "truth_score": 5,
        "notes": "八代亜紀の港シリーズ代表作"
    },
    {
        "title": "古城",
        "artist": "三橋美智也",
        "year": 1959,
        "genre": "演歌",
        "emotion_type": "歴史/郷愁/廃墟の美",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "廃れた城への郷愁。無常観という日本的感性",
        "lyrics_keywords": ["城", "古い", "月", "歴史"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "日本の無常観を城に投影した文化的名作"
    },
    {
        "title": "達者でな",
        "artist": "三橋美智也",
        "year": 1960,
        "genre": "演歌",
        "emotion_type": "別れ/応援/哀愁",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "「元気でいろ」という別れの言葉の純粋な温かさ",
        "lyrics_keywords": ["達者", "別れ", "元気", "故郷"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "東北弁の温かみが感情の真実を際立たせる"
    },
    {
        "title": "帰ろかな",
        "artist": "北島三郎",
        "year": 1965,
        "genre": "演歌",
        "emotion_type": "望郷/迷い/故郷",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "帰るか帰らないかの迷い。離郷者の永遠のジレンマ",
        "lyrics_keywords": ["帰る", "故郷", "迷う", "酒"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "日本の高度成長期の出稼ぎ労働者の心情"
    },
    {
        "title": "居酒屋",
        "artist": "木の実ナナ・五木ひろし",
        "year": 1982,
        "genre": "演歌",
        "emotion_type": "孤独/酒/繋がり",
        "emotion_function": "麻痺",
        "consciousness_level": 4,
        "consciousness_notes": "居酒屋という麻痺空間での一時的なつながり",
        "lyrics_keywords": ["居酒屋", "酒", "二人", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 6,
        "notes": "男女デュエット演歌の傑作。居酒屋という日本的慰め空間"
    },
    {
        "title": "浪花節だよ人生は",
        "artist": "細川たかし",
        "year": 1984,
        "genre": "演歌",
        "emotion_type": "人生観/涙/義理人情",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "浪花節＝義理人情。日本的共同体倫理への感情的同化",
        "lyrics_keywords": ["人生", "涙", "義理", "情"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 5,
        "notes": "日本的「義理と人情」の感情構造の歌謡化"
    },
    {
        "title": "酒と泪と男と女",
        "artist": "河島英五",
        "year": 1976,
        "genre": "フォーク/歌謡曲",
        "emotion_type": "酒/感傷/人生",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "酒を飲みながら本音を語る解放。フォーク的な正直さ",
        "lyrics_keywords": ["酒", "涙", "男", "女", "飲む"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "酒を介した人間の本音の解放。男女の本質への洞察"
    },
    {
        "title": "時の流れに身をまかせ",
        "artist": "テレサ・テン",
        "year": 1986,
        "genre": "歌謡曲",
        "emotion_type": "愛/献身/服従",
        "emotion_function": "麻痺",
        "consciousness_level": 2,
        "consciousness_notes": "「あなたのものになりたい」という完全な自己消滅。魂の奴隷化",
        "lyrics_keywords": ["時", "流れ", "あなた", "ものになりたい"],
        "cultural_impact": "大",
        "soul_freedom_score": 2,
        "truth_score": 4,
        "notes": "美しいが危険な歌。自己を捨てた完全な愛の服従は麻痺の極致"
    },
    {
        "title": "つぐない",
        "artist": "テレサ・テン",
        "year": 1984,
        "genre": "歌謡曲",
        "emotion_type": "罪悪感/償い/愛",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "罪悪感による自己麻痺。愛のための自己罰",
        "lyrics_keywords": ["つぐない", "罪", "許し", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 5,
        "notes": "テレサ・テン三部作の第一弾。罪悪感という感情の歌謡化"
    },
    {
        "title": "愛人",
        "artist": "テレサ・テン",
        "year": 1985,
        "genre": "歌謡曲",
        "emotion_type": "不倫/禁断の愛/甘い罪",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "愛人という社会的タブーの甘美化。罪の麻痺",
        "lyrics_keywords": ["愛人", "秘密", "甘い", "罪"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 5,
        "notes": "禁断の愛の麻痺的な美しさ。テレサ三部作完成"
    },
    {
        "title": "おふくろさん",
        "artist": "森進一",
        "year": 1971,
        "genre": "演歌",
        "emotion_type": "母/感謝/郷愁",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "母への感謝という普遍的感情。ただし「母」の理想化の側面も",
        "lyrics_keywords": ["おふくろ", "母", "ありがとう", "苦労"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "日本演歌の母への感謝の定番。川内康範との確執も歴史の一部"
    },
    {
        "title": "冬のリビエラ",
        "artist": "森進一",
        "year": 1982,
        "genre": "歌謡曲",
        "emotion_type": "別れ/冬/大人の愛",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "松本隆・大滝詠一作品。洗練された別れの表現",
        "lyrics_keywords": ["冬", "リビエラ", "別れ", "海"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "ニューミュージックと演歌の融合点"
    },
    {
        "title": "悲しみにさよなら",
        "artist": "安全地帯",
        "year": 1985,
        "genre": "歌謡曲/ロック",
        "emotion_type": "悲しみ/別れ/再生",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "悲しみへの「さよなら」という積極的な別れ。麻痺でなく解放",
        "lyrics_keywords": ["悲しみ", "さよなら", "玉置浩二"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "玉置浩二の声が感情の解放を後押しする"
    },
    {
        "title": "ワインレッドの心",
        "artist": "安全地帯",
        "year": 1983,
        "genre": "歌謡曲/ロック",
        "emotion_type": "官能/大人の愛",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "官能的な愛の表現。大人の世界への扉",
        "lyrics_keywords": ["ワイン", "赤", "心", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "80年代大人の恋愛の象徴。井上陽水プロデュース"
    },
    {
        "title": "恋人よ",
        "artist": "五木ひろし",
        "year": 1980,
        "genre": "演歌",
        "emotion_type": "別れ/愛惜",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "恋人への別れの言葉。別れを受け入れる演歌的成熟",
        "lyrics_keywords": ["恋人", "別れ", "愛", "さようなら"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "五木ひろしの代表作。別れの成熟した受容"
    },
    {
        "title": "細雪",
        "artist": "吉幾三",
        "year": 1988,
        "genre": "演歌",
        "emotion_type": "春の雪/無常/美",
        "emotion_function": "昇華",
        "consciousness_level": 7,
        "consciousness_notes": "谷崎潤一郎の小説を昇華。儚さを美として受け入れる",
        "lyrics_keywords": ["細雪", "春", "儚い", "美"],
        "cultural_impact": "中",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "文学と演歌の高次元での融合"
    },
    {
        "title": "哀愁でいと",
        "artist": "田原俊彦",
        "year": 1980,
        "genre": "アイドル歌謡",
        "emotion_type": "青春/哀愁/アイドル",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "アイドルシステムの典型。消費される若さと感情",
        "lyrics_keywords": ["哀愁", "君", "青春"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 3,
        "notes": "ジャニーズ第一世代。アイドル産業の始動期"
    },
    {
        "title": "夢・旅人",
        "artist": "前川清",
        "year": 1979,
        "genre": "演歌",
        "emotion_type": "旅/夢/孤独",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "旅人という自由な存在への憧れ",
        "lyrics_keywords": ["夢", "旅人", "道", "孤独"],
        "cultural_impact": "中",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "前川清の哀愁ある声と旅の哲学"
    },
    {
        "title": "港町ブルース",
        "artist": "森進一",
        "year": 1969,
        "genre": "演歌",
        "emotion_type": "港/ブルース/孤独",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "港町の哀愁と孤独。ブルース的感情の日本的表現",
        "lyrics_keywords": ["港", "ブルース", "一人", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 6,
        "notes": "演歌とブルースの接点。孤独という普遍的感情"
    },
    {
        "title": "喝采",
        "artist": "ちあきなおみ",
        "year": 1972,
        "genre": "演歌/歌謡曲",
        "emotion_type": "舞台/喪失/演じること",
        "emotion_function": "昇華",
        "consciousness_level": 9,
        "consciousness_notes": "舞台で演じる中に届く恋人の死の報せ。芸と人生の交錯",
        "lyrics_keywords": ["喝采", "舞台", "訃報", "演じる"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 9,
        "notes": "日本歌謡曲最高傑作の一つ。芸能者の宿命と人間的悲劇"
    },
    {
        "title": "黄昏のビギン",
        "artist": "ちあきなおみ",
        "year": 1959,
        "genre": "歌謡曲",
        "emotion_type": "夕暮れ/恋/哀愁",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "ラテンリズムと日本的哀愁の見事な融合。永遠の夕暮れの美",
        "lyrics_keywords": ["黄昏", "ビギン", "恋", "夕暮れ"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "中島みゆきが絶賛。時代を超えた普遍的美しさ"
    },
    {
        "title": "夜へ急ぐ人",
        "artist": "ちあきなおみ",
        "year": 1974,
        "genre": "演歌/歌謡曲",
        "emotion_type": "危険な愛/狂気/夜",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "狂気的な愛への突進。理性を超えた感情の爆発",
        "lyrics_keywords": ["夜", "急ぐ", "狂気", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "ちあきなおみの凄みの頂点。歌謡曲の中の本物の狂気"
    },
    {
        "title": "なごり雪",
        "artist": "かぐや姫/イルカ",
        "year": 1974,
        "genre": "フォーク",
        "emotion_type": "別れ/春の予感/儚さ",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "最後の雪という象徴と別れの融合。儚さの中の美",
        "lyrics_keywords": ["なごり雪", "春", "別れ", "ホーム"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "伊勢正三の傑作。日本の別れの美学の極致"
    },
    {
        "title": "翼をください",
        "artist": "赤い鳥",
        "year": 1971,
        "genre": "フォーク",
        "emotion_type": "自由への渇望/飛翔",
        "emotion_function": "覚醒",
        "consciousness_level": 8,
        "consciousness_notes": "「翼」というメタファーは魂の自由への渇望そのもの",
        "lyrics_keywords": ["翼", "空", "自由", "飛ぶ"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 8,
        "notes": "合唱曲として定着。魂の自由への普遍的な呼びかけ"
    },
    {
        "title": "心の旅",
        "artist": "チューリップ",
        "year": 1973,
        "genre": "フォーク/ポップス",
        "emotion_type": "旅/心の冒険",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "内なる旅という心の解放。外への旅ではなく内への旅",
        "lyrics_keywords": ["心", "旅", "夜明け", "風"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "財津和夫のポップセンスとフォーク精神の融合"
    },
]

# ===== 2. 1960-70年代歌謡曲 (50曲以上) =====
KAYOKYOKU_6070 = [
    {
        "title": "スーダラ節",
        "artist": "植木等",
        "year": 1961,
        "genre": "歌謡曲/コミック",
        "emotion_type": "脱力/諦め/笑い",
        "emotion_function": "解放",
        "consciousness_level": 9,
        "consciousness_notes": "「わかっちゃいるけどやめられない」は人間の実存的正直さ。笑いによる真実の解放",
        "lyrics_keywords": ["スーダラ", "わかっちゃいる", "やめられない"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 9,
        "notes": "植木等の「無責任シリーズ」の核心。高度経済成長への皮肉的解放感"
    },
    {
        "title": "恋の奴隷",
        "artist": "奥村チヨ",
        "year": 1969,
        "genre": "歌謡曲",
        "emotion_type": "服従/官能/愛の奴隷",
        "emotion_function": "麻痺",
        "consciousness_level": 1,
        "consciousness_notes": "「奴隷になりたい」という完全な自己消去の欲望。魂の売渡し",
        "lyrics_keywords": ["奴隷", "恋", "あなた", "服従"],
        "cultural_impact": "大",
        "soul_freedom_score": 1,
        "truth_score": 5,
        "notes": "タイトルが全てを語る。自己を消した愛という最も危険な感情"
    },
    {
        "title": "夜明けのスキャット",
        "artist": "由紀さおり",
        "year": 1969,
        "genre": "歌謡曲",
        "emotion_type": "夜明け/純粋/声の美",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "言葉を超えた声そのものの美しさ。スキャットという言語を超えた表現",
        "lyrics_keywords": ["夜明け", "ルールル", "スキャット"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "言語を超えた音楽の純粋性。後年の世界的評価は必然"
    },
    {
        "title": "花の首飾り",
        "artist": "ザ・タイガース",
        "year": 1968,
        "genre": "グループサウンズ",
        "emotion_type": "純愛/青春/花",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "GSブームの純粋な青春讃歌",
        "lyrics_keywords": ["花", "首飾り", "愛", "春"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "グループサウンズ最大のヒット。日本のビートルズ熱の頂点"
    },
    {
        "title": "君といつまでも",
        "artist": "加山雄三",
        "year": 1965,
        "genre": "歌謡曲",
        "emotion_type": "愛/永遠/誓い",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "「幸せだなあ」という素直な幸福感。感情の素直な表出",
        "lyrics_keywords": ["君", "いつまでも", "幸せ", "永遠"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "加山雄三の「若大将」的純粋さ。昭和の幸福観の結晶"
    },
    {
        "title": "禁じられた恋",
        "artist": "野口五郎",
        "year": 1972,
        "genre": "歌謡曲",
        "emotion_type": "禁断の愛/苦しさ",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "禁断の愛の苦しさ。規範と感情の衝突",
        "lyrics_keywords": ["禁じられた", "恋", "苦しい", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "新御三家の一人の代表曲"
    },
    {
        "title": "わたしの城下町",
        "artist": "小柳ルミ子",
        "year": 1971,
        "genre": "歌謡曲",
        "emotion_type": "故郷/純愛/城下町",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "地方と純愛の組み合わせ。日本の原風景への共鳴",
        "lyrics_keywords": ["城下町", "私", "恋", "町"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "デビュー曲で100万枚。歌謡曲黄金期の象徴"
    },
    {
        "title": "よいとまけの唄",
        "artist": "美輪明宏",
        "year": 1965,
        "genre": "歌謡曲",
        "emotion_type": "差別/誇り/母/労働",
        "emotion_function": "覚醒",
        "consciousness_level": 10,
        "consciousness_notes": "被差別階級の母への誇りと社会批判。日本歌謡史上最も意識高い歌の一つ",
        "lyrics_keywords": ["よいとまけ", "母", "差別", "誇り", "泥"],
        "cultural_impact": "大",
        "soul_freedom_score": 10,
        "truth_score": 10,
        "notes": "NHK放送禁止曲だった。差別という真実を真正面から歌った勇気"
    },
    {
        "title": "ヨイトマケの唄（美輪明宏版）",
        "artist": "丸山明宏（美輪明宏）",
        "year": 1965,
        "genre": "歌謡曲",
        "emotion_type": "貧困/誇り/愛",
        "emotion_function": "覚醒",
        "consciousness_level": 10,
        "consciousness_notes": "社会の底辺で生きる人間の尊厳の宣言",
        "lyrics_keywords": ["母ちゃん", "働く", "泥", "誇り"],
        "cultural_impact": "大",
        "soul_freedom_score": 10,
        "truth_score": 10,
        "notes": "同曲の別バージョン記録"
    },
    {
        "title": "ブルー・シャトウ",
        "artist": "ジャッキー吉川とブルーコメッツ",
        "year": 1967,
        "genre": "グループサウンズ",
        "emotion_type": "夢/城/ロマン",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "GSブームの夢とロマンの象徴",
        "lyrics_keywords": ["ブルー", "城", "夢", "空"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "第9回日本レコード大賞受賞。GS全盛期の象徴"
    },
    {
        "title": "伊勢佐木町ブルース",
        "artist": "青江三奈",
        "year": 1968,
        "genre": "歌謡曲",
        "emotion_type": "官能/夜/都市",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "ため息交じりの官能性。女性の夜の解放",
        "lyrics_keywords": ["伊勢佐木町", "ブルース", "夜", "ため息"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "艶っぽいため息がトレードマーク。昭和官能歌謡の傑作"
    },
    {
        "title": "白いブランコ",
        "artist": "ビリー・バンバン",
        "year": 1969,
        "genre": "フォーク",
        "emotion_type": "青春/純愛/切なさ",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "ブランコという無垢な象徴と青春の切なさ",
        "lyrics_keywords": ["ブランコ", "白い", "君", "青春"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "フォーク黎明期の名曲"
    },
    {
        "title": "圭子の夢は夜ひらく",
        "artist": "藤圭子",
        "year": 1970,
        "genre": "演歌",
        "emotion_type": "暗い運命/怨念/夜の女",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "夜に生きる女の運命。暗さを正面から肯定する勇気",
        "lyrics_keywords": ["夢", "夜", "ひらく", "運命"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 8,
        "notes": "宇多田ヒカルの母。暗い出自を力に変えた孤高の歌手"
    },
    {
        "title": "また逢う日まで",
        "artist": "尾崎紀世彦",
        "year": 1971,
        "genre": "歌謡曲",
        "emotion_type": "別れ/再会の誓い",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "別れを悲しみではなく再会の誓いとして昇華する",
        "lyrics_keywords": ["また", "逢う", "日まで", "別れ"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "尾崎紀世彦の歌唱力が感情を直接届ける"
    },
    {
        "title": "わかれうた",
        "artist": "中島みゆき",
        "year": 1977,
        "genre": "フォーク",
        "emotion_type": "別れ/女の強さ",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "泣かずに立ち去る女の強さ。感情の抑制ではなく昇華",
        "lyrics_keywords": ["別れ", "うた", "泣く", "立つ"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "中島みゆきの才能が初めて大衆に届いた曲"
    },
    {
        "title": "岬めぐり",
        "artist": "山本コータローとウィークエンド",
        "year": 1974,
        "genre": "フォーク",
        "emotion_type": "旅/思い出/失恋",
        "emotion_function": "昇華",
        "consciousness_level": 7,
        "consciousness_notes": "旅の中で失恋を昇華する。移動による感情の解放",
        "lyrics_keywords": ["岬", "めぐる", "バス", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "フォークの旅の美学の代表作"
    },
    {
        "title": "季節の中で",
        "artist": "松山千春",
        "year": 1978,
        "genre": "フォーク",
        "emotion_type": "失恋/孤独/受容",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "失恋を季節の変化として受け入れる。自然との共鳴による癒し",
        "lyrics_keywords": ["季節", "愛", "孤独", "中で"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "北海道の自然から生まれたフォークの誠実さ"
    },
    {
        "title": "恋",
        "artist": "松山千春",
        "year": 1978,
        "genre": "フォーク",
        "emotion_type": "恋の痛み/真摯",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "シンプルだが感情の真実がある。北海道的な誠実さ",
        "lyrics_keywords": ["恋", "あなた", "痛い", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "松山千春の代表的恋愛フォーク"
    },
    {
        "title": "なぜ（君は行ってしまうのか）",
        "artist": "赤い鳥",
        "year": 1972,
        "genre": "フォーク",
        "emotion_type": "別れの疑問/純粋",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "「なぜ」という問いは感情の真摯な表現",
        "lyrics_keywords": ["なぜ", "君", "行く", "別れ"],
        "cultural_impact": "中",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "赤い鳥の美しいハーモニーが感情を昇華"
    },
    {
        "title": "YOUNG MAN (Y.M.C.A.)",
        "artist": "西城秀樹",
        "year": 1979,
        "genre": "歌謡曲/ポップス",
        "emotion_type": "元気/青春/踊り",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "身体を動かすことへの純粋な喜び。振付という身体的解放",
        "lyrics_keywords": ["YOUNG", "MAN", "YMCA", "元気"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 5,
        "notes": "外来ポップスの日本的消化の成功例。身体の解放"
    },
    {
        "title": "傷だらけの天使",
        "artist": "野口五郎",
        "year": 1974,
        "genre": "歌謡曲",
        "emotion_type": "傷/純粋/再生",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "傷ついた純粋さへの共鳴",
        "lyrics_keywords": ["傷", "天使", "純粋", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "新御三家の中で最も詩的な表現を持つ"
    },
    {
        "title": "勝手にしやがれ",
        "artist": "沢田研二",
        "year": 1977,
        "genre": "歌謡曲",
        "emotion_type": "諦め/反抗/かっこよさ",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "「勝手にしろ」という開き直りは感情の解放。カッコ悪さをカッコよさに変換",
        "lyrics_keywords": ["勝手", "しやがれ", "別れ", "男"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "レコード大賞受賞。別れの諦めをスタイルに昇華したジュリー"
    },
    {
        "title": "TOKIO",
        "artist": "沢田研二",
        "year": 1980,
        "genre": "歌謡曲/ロック",
        "emotion_type": "都市/自由/飛翔",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "東京という都市への反抗的な飛翔。加藤和彦の実験的編曲",
        "lyrics_keywords": ["TOKIO", "飛ぶ", "東京", "自由"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "紙ヒコーキのパフォーマンスも含め日本歌謡史の転換点"
    },
    {
        "title": "異邦人",
        "artist": "久保田早紀",
        "year": 1979,
        "genre": "歌謡曲",
        "emotion_type": "異邦/孤独/異国情緒",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "「シルクロードのかなた」という異界への憧憬。現実からの解放",
        "lyrics_keywords": ["異邦人", "シルクロード", "子供たち", "砂漠"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "日本の歌謡曲が世界への憧れを持った瞬間"
    },
    {
        "title": "木綿のハンカチーフ",
        "artist": "太田裕美",
        "year": 1975,
        "genre": "フォーク/歌謡曲",
        "emotion_type": "都市と田舎/変化/別れ",
        "emotion_function": "共鳴",
        "consciousness_level": 8,
        "consciousness_notes": "都市化による価値観の変容を男女の往復書簡で描く。時代の真実",
        "lyrics_keywords": ["木綿", "ハンカチーフ", "東京", "帰らない"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "松本隆の傑作詞。高度成長期の価値観変容の音楽的証言"
    },
    {
        "title": "なんでもないや",
        "artist": "RADWIMPS",
        "year": 2016,
        "genre": "J-pop/アニメ",
        "emotion_type": "運命/出会い/生きる意味",
        "emotion_function": "覚醒",
        "consciousness_level": 8,
        "consciousness_notes": "「君の名は」の文脈で時間を超えた愛と存在への問い",
        "lyrics_keywords": ["なんでもない", "出会い", "運命", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "映画と一体化した新世代の感情体験"
    },
    {
        "title": "UFO",
        "artist": "ピンク・レディー",
        "year": 1977,
        "genre": "歌謡曲",
        "emotion_type": "異星人/自由/ユーフォリア",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "宇宙人との接触という非日常への憧れ。現実からの解放",
        "lyrics_keywords": ["UFO", "宇宙人", "来た", "光"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 5,
        "notes": "ピンクレディーの振付は身体的解放のメカニズム"
    },
    {
        "title": "渚のシンドバッド",
        "artist": "ピンク・レディー",
        "year": 1977,
        "genre": "歌謡曲",
        "emotion_type": "冒険/恋/夏",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "夏の冒険への純粋な高揚感",
        "lyrics_keywords": ["渚", "シンドバッド", "夏", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "ピンクレディー黄金期の代表作"
    },
    {
        "title": "別れの朝",
        "artist": "ペドロ＆カプリシャス",
        "year": 1971,
        "genre": "歌謡曲",
        "emotion_type": "別れ/朝/終焉",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "朝という時間軸と別れの組み合わせ。感情の繊細な描写",
        "lyrics_keywords": ["別れ", "朝", "二人", "終わり"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "前川清が在籍した時期の名曲"
    },
    {
        "title": "ケメ子の唄",
        "artist": "ザ・ダーツ",
        "year": 1968,
        "genre": "歌謡曲/コミック",
        "emotion_type": "笑い/日常/愛着",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "コミックソングという軽さの中の人情",
        "lyrics_keywords": ["ケメ子", "猫", "好き"],
        "cultural_impact": "中",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "GS時代のコミックソングの代表"
    },
    {
        "title": "学生街の喫茶店",
        "artist": "ガロ",
        "year": 1972,
        "genre": "フォーク",
        "emotion_type": "青春/喫茶店/ノスタルジー",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "「あの頃の僕たちは何もわからなかった」という成熟した振り返り",
        "lyrics_keywords": ["学生", "喫茶店", "ギター", "あの頃"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "青春への深い洞察。喫茶店という場所の記憶の力"
    },
    {
        "title": "あの素晴らしい愛をもう一度",
        "artist": "北山修＆加藤和彦",
        "year": 1971,
        "genre": "フォーク",
        "emotion_type": "失われた愛/懐古/普遍",
        "emotion_function": "共鳴",
        "consciousness_level": 8,
        "consciousness_notes": "失われた愛への普遍的な哀悼。フォーク精神の核心",
        "lyrics_keywords": ["愛", "もう一度", "素晴らしい", "あの頃"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "精神科医・北山修と天才加藤和彦のコラボ。時代を超えた名曲"
    },
    {
        "title": "風",
        "artist": "はしだのりひことシューベルツ",
        "year": 1969,
        "genre": "フォーク",
        "emotion_type": "風/人の一生/哲学",
        "emotion_function": "覚醒",
        "consciousness_level": 9,
        "consciousness_notes": "「人は誰もただ一人旅に出て」という存在論的問い。仏教的無常観",
        "lyrics_keywords": ["風", "旅", "一人", "人生"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 9,
        "notes": "フォーク哲学の頂点。生の孤独という真実への直視"
    },
    {
        "title": "悲しくてやりきれない",
        "artist": "フォーク・クルセダーズ",
        "year": 1968,
        "genre": "フォーク",
        "emotion_type": "悲しみ/怒り/正直",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "感情を素直に言語化する。「やりきれない」という感情の正直な表現",
        "lyrics_keywords": ["悲しい", "やりきれない", "涙", "怒り"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "加藤和彦・北山修・坂崎幸之助。感情の正直な表現の原点"
    },
    {
        "title": "今日の日はさようなら",
        "artist": "森山良子",
        "year": 1966,
        "genre": "フォーク",
        "emotion_type": "別れ/感謝/一日の終わり",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "一日の終わりへの感謝と別れ。普遍的な人生の哲学",
        "lyrics_keywords": ["今日", "さようなら", "友", "また"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "卒業式の定番曲。別れへの真摯な感謝"
    },
    {
        "title": "シクラメンのかほり",
        "artist": "布施明",
        "year": 1975,
        "genre": "歌謡曲",
        "emotion_type": "愛/花/純粋",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "花の香りという嗅覚的愛の表現。感情の繊細さ",
        "lyrics_keywords": ["シクラメン", "かほり", "愛", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "小椋佳作詞作曲。繊細な感情表現の歌謡曲"
    },
    {
        "title": "男の子女の子",
        "artist": "郷ひろみ",
        "year": 1972,
        "genre": "歌謡曲/アイドル",
        "emotion_type": "青春/性/ジェンダー",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "ジェンダー規範の軽い越境。郷ひろみの中性的魅力",
        "lyrics_keywords": ["男の子", "女の子", "好き", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "郷ひろみの中性的アイドル性の始まり"
    },
    {
        "title": "甘い生活",
        "artist": "野口五郎",
        "year": 1976,
        "genre": "歌謡曲",
        "emotion_type": "甘い愛/幸福感",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "甘さという感覚の愛への投影",
        "lyrics_keywords": ["甘い", "生活", "君", "幸せ"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "70年代歌謡曲の甘い世界の代表"
    },
    {
        "title": "喝采（ちあきなおみ）",
        "artist": "ちあきなおみ",
        "year": 1972,
        "genre": "歌謡曲",
        "emotion_type": "喪失/舞台/人生",
        "emotion_function": "昇華",
        "consciousness_level": 9,
        "consciousness_notes": "舞台で演じながら恋人の死を知る。芸術家の孤独と宿命",
        "lyrics_keywords": ["喝采", "拍手", "知らせ", "恋人"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 10,
        "notes": "演じることと生きることの境界を消した傑作"
    },
    {
        "title": "朝の光の中で",
        "artist": "吉田拓郎",
        "year": 1970,
        "genre": "フォーク",
        "emotion_type": "反抗/若さ/自由",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "フォーク世代の権力への反抗と自由への渇望",
        "lyrics_keywords": ["朝", "光", "自由", "若い"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "吉田拓郎フォーク革命の始まり"
    },
    {
        "title": "結婚しようよ",
        "artist": "吉田拓郎",
        "year": 1972,
        "genre": "フォーク",
        "emotion_type": "愛/プロポーズ/率直",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "「ぼくの髪が肩まで伸びたら」という直接的プロポーズ。飾らない愛",
        "lyrics_keywords": ["結婚", "髪", "肩", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 8,
        "notes": "長髪という反抗の象徴を愛のメタファーに転換した革命的曲"
    },
    {
        "title": "人生の並木路",
        "artist": "二葉あき子",
        "year": 1936,
        "genre": "歌謡曲",
        "emotion_type": "人生/希望/忍耐",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "戦前歌謡曲の人生観。苦難を耐えるという価値観",
        "lyrics_keywords": ["人生", "並木路", "涙", "希望"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "戦前から愛される日本的忍耐の歌"
    },
    {
        "title": "見上げてごらん夜の星を",
        "artist": "坂本九",
        "year": 1963,
        "genre": "歌謡曲",
        "emotion_type": "希望/星/孤独の共有",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "夜空を共有することで孤独を和らげる。星という普遍的象徴",
        "lyrics_keywords": ["星", "夜空", "見上げる", "二人"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "九ちゃんの優しさが星への誘いに込められた"
    },
    {
        "title": "ひとり寝の子守唄",
        "artist": "美空ひばり",
        "year": 1962,
        "genre": "歌謡曲",
        "emotion_type": "孤独/子守唄/自己慰め",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "自分自身への子守唄。孤独の中の自己愛",
        "lyrics_keywords": ["子守唄", "一人", "眠る", "夜"],
        "cultural_impact": "中",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ひばりの孤独感の表現の一面"
    },
    {
        "title": "どうにもとまらない",
        "artist": "山本リンダ",
        "year": 1972,
        "genre": "歌謡曲",
        "emotion_type": "官能/衝動/エロス",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "「止まらない」という衝動の表現。身体的欲望の解放",
        "lyrics_keywords": ["どうにも", "とまらない", "燃える", "情熱"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "阿久悠×都倉俊一のヒット製造機の傑作"
    },
    {
        "title": "真夜中のギター",
        "artist": "千賀かほる",
        "year": 1969,
        "genre": "歌謡曲",
        "emotion_type": "孤独/夜/ギター",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "深夜のギターという孤独な音楽行為への共鳴",
        "lyrics_keywords": ["真夜中", "ギター", "孤独", "夜"],
        "cultural_impact": "中",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "深夜という時間帯と孤独の音楽"
    },
    {
        "title": "22才の別れ",
        "artist": "風",
        "year": 1975,
        "genre": "フォーク",
        "emotion_type": "若い別れ/成長/切なさ",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "「あなたが変わったのではなく私が変わった」という成熟した洞察",
        "lyrics_keywords": ["22才", "別れ", "変わった", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "伊勢正三の最高傑作。成長による別れという真実の描写"
    },
    {
        "title": "赤色エレジー",
        "artist": "あがた森魚",
        "year": 1972,
        "genre": "フォーク",
        "emotion_type": "貧困/恋/哀愁",
        "emotion_function": "昇華",
        "consciousness_level": 9,
        "consciousness_notes": "貧しい恋人たちの哀愁。フォーク左翼の感性と個人の恋愛の融合",
        "lyrics_keywords": ["赤色", "エレジー", "貧しい", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 9,
        "notes": "日本フォーク史上最も実験的な一発ヒット"
    },
]

# ===== 3. 1980年代アイドル (40曲) =====
IDOL_80S = [
    {
        "title": "青い珊瑚礁",
        "artist": "松田聖子",
        "year": 1980,
        "genre": "アイドル",
        "emotion_type": "夏/憧れ/純粋",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "完璧に計算されたアイドル像。純粋さという商品",
        "lyrics_keywords": ["珊瑚礁", "青い", "夏", "海"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "松田聖子という商品の完成。アイドル産業の頂点"
    },
    {
        "title": "裸足の季節",
        "artist": "松田聖子",
        "year": 1980,
        "genre": "アイドル",
        "emotion_type": "青春/自由/少女",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "裸足という自由の象徴。少女の一時的解放感",
        "lyrics_keywords": ["裸足", "季節", "走る", "自由"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 4,
        "notes": "聖子のデビュー曲。裸足という解放のメタファー"
    },
    {
        "title": "渚のバルコニー",
        "artist": "松田聖子",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "夏/恋/バカンス",
        "emotion_function": "共鳴",
        "consciousness_level": 3,
        "consciousness_notes": "夏の恋愛ファンタジー。アイドルという夢の商品",
        "lyrics_keywords": ["渚", "バルコニー", "夏", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 3,
        "notes": "松本隆が聖子のために書いた夏の幻想"
    },
    {
        "title": "SWEET MEMORIES",
        "artist": "松田聖子",
        "year": 1983,
        "genre": "アイドル/ポップス",
        "emotion_type": "甘い記憶/孤独",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "甘い記憶という普遍的感情。アイドルを超えた普遍性",
        "lyrics_keywords": ["SWEET", "記憶", "思い出", "孤独"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "アイドル聖子が最も人間的な感情を見せた曲"
    },
    {
        "title": "赤いスイートピー",
        "artist": "松田聖子",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "純愛/憧れ/少女",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "「汽車に乗って」という逃避への憧れ。松本隆の詩的世界",
        "lyrics_keywords": ["スイートピー", "赤い", "春", "汽車"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 5,
        "notes": "松本隆の最高傑作詞の一つ。アイドル詞の文学性"
    },
    {
        "title": "スローモーション",
        "artist": "中森明菜",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "純愛/時間/ゆっくり",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "スローモーションという時間感覚の恋愛への応用",
        "lyrics_keywords": ["スローモーション", "時間", "君", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "明菜のデビュー曲。秘めた内面の片鱗"
    },
    {
        "title": "少女A",
        "artist": "中森明菜",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "反抗/危険/少女の闇",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "「少女A」という匿名性が持つ反抗。アイドルとしての本能的な逸脱",
        "lyrics_keywords": ["少女", "危険", "ほら", "反抗"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "明菜の本質的な危険性の最初の開花"
    },
    {
        "title": "飾りじゃないのよ涙は",
        "artist": "中森明菜",
        "year": 1984,
        "genre": "アイドル",
        "emotion_type": "本物の感情/反アイドル",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "「飾りじゃない」という言明がアイドルの虚構への反抗",
        "lyrics_keywords": ["飾り", "涙", "本物", "叫ぶ"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "アイドルシステムへの内側からの反乱。明菜の真骨頂"
    },
    {
        "title": "サザン・ウィンド",
        "artist": "中森明菜",
        "year": 1984,
        "genre": "アイドル",
        "emotion_type": "旅/自由/南の風",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "南の風という自由への憧れ",
        "lyrics_keywords": ["南", "風", "旅", "自由"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 5,
        "notes": "明菜の多様な表現力の一面"
    },
    {
        "title": "ミ・アモーレ",
        "artist": "中森明菜",
        "year": 1985,
        "genre": "アイドル/J-pop",
        "emotion_type": "情熱/ラテン/愛",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "異文化の情熱の取り込みによる自己解放",
        "lyrics_keywords": ["ミ・アモーレ", "愛", "情熱", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 5,
        "notes": "レコード大賞受賞。明菜の国際的表現への挑戦"
    },
    {
        "title": "仮面舞踏会",
        "artist": "少年隊",
        "year": 1985,
        "genre": "アイドル",
        "emotion_type": "仮面/変身/ダンス",
        "emotion_function": "麻痺",
        "consciousness_level": 4,
        "consciousness_notes": "仮面＝アイドルという虚構の肯定。ダンスによる感情の表面的消費",
        "lyrics_keywords": ["仮面", "舞踏会", "踊る", "夜"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "ジャニーズのダンス路線の確立"
    },
    {
        "title": "君だけに",
        "artist": "少年隊",
        "year": 1988,
        "genre": "アイドル",
        "emotion_type": "一途な愛/献身",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "「君だけ」という排他的愛。執着の美化",
        "lyrics_keywords": ["君だけ", "愛", "一人", "永遠"],
        "cultural_impact": "大",
        "soul_freedom_score": 3,
        "truth_score": 3,
        "notes": "アイドル的愛の理想化。排他的愛の危険性"
    },
    {
        "title": "あの頃へ",
        "artist": "近藤真彦",
        "year": 1985,
        "genre": "アイドル",
        "emotion_type": "郷愁/青春/あの頃",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "過去への執着。マッチのワイルドさも計算された商品",
        "lyrics_keywords": ["あの頃", "青春", "戻る", "懐かしい"],
        "cultural_impact": "中",
        "soul_freedom_score": 3,
        "truth_score": 3,
        "notes": "マッチの郷愁歌謡"
    },
    {
        "title": "ギンギラギンにさりげなく",
        "artist": "近藤真彦",
        "year": 1981,
        "genre": "アイドル",
        "emotion_type": "男気/反抗/さりげなさ",
        "emotion_function": "解放",
        "consciousness_level": 4,
        "consciousness_notes": "「さりげなく」という矛盾した男らしさ。アイドル的男性像",
        "lyrics_keywords": ["ギンギラギン", "さりげなく", "男"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "マッチのデビュー曲で大ヒット。80年代男性アイドルの原型"
    },
    {
        "title": "林檎殺人事件",
        "artist": "郷ひろみ＆樹木希林",
        "year": 1978,
        "genre": "アイドル/コミック",
        "emotion_type": "コミカル/パロディ",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "アイドルとコミックの組み合わせ。自己をパロディ化する知性",
        "lyrics_keywords": ["林檎", "殺人", "事件", "コミカル"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "アイドル文化へのメタ的な視点を持つ異色作"
    },
    {
        "title": "時をかける少女",
        "artist": "原田知世",
        "year": 1983,
        "genre": "アイドル",
        "emotion_type": "時間/夢/少女",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "時間を超える想像力。SF的な感情の解放",
        "lyrics_keywords": ["時", "少女", "かける", "夢"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "映画タイアップ。原田知世の独特な世界観"
    },
    {
        "title": "なんてったってアイドル",
        "artist": "小泉今日子",
        "year": 1985,
        "genre": "アイドル",
        "emotion_type": "アイドル性への自覚/自己パロディ",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "「なんてったってアイドル」という自己言及。アイドルを演じることの自覚",
        "lyrics_keywords": ["アイドル", "なんてったって", "キョンキョン"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "アイドルというシステムへのメタ的な参加。小泉今日子の知性"
    },
    {
        "title": "あなたに会えてよかった",
        "artist": "小泉今日子",
        "year": 1991,
        "genre": "J-pop",
        "emotion_type": "感謝/出会い/愛",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "出会いへの純粋な感謝",
        "lyrics_keywords": ["あなた", "会えた", "よかった", "感謝"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "キョンキョンのアイドル期最後の輝き"
    },
    {
        "title": "スシ食いねェ!",
        "artist": "シブがき隊",
        "year": 1986,
        "genre": "アイドル/コミック",
        "emotion_type": "食文化/楽しさ/バカバカしさ",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "「寿司」という日常的なものへの屈託のない喜び",
        "lyrics_keywords": ["スシ", "食いねェ", "とびきり"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "バカバカしさが正直な喜びになる瞬間"
    },
    {
        "title": "春よ、来い",
        "artist": "松任谷由実",
        "year": 1994,
        "genre": "J-pop",
        "emotion_type": "春の訪れ/再生/希望",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "春という再生の季節への呼びかけ。ユーミンの自然観と感情の融合",
        "lyrics_keywords": ["春", "来い", "光", "再生"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "ユーミンの晩期傑作。季節と感情の永遠の融合"
    },
    {
        "title": "ひこうき雲",
        "artist": "荒井由実",
        "year": 1973,
        "genre": "J-pop/フォーク",
        "emotion_type": "死/純粋/切なさ",
        "emotion_function": "昇華",
        "consciousness_level": 9,
        "consciousness_notes": "若くして亡くなった人への詩。死を否定せず美として昇華",
        "lyrics_keywords": ["ひこうき雲", "空", "消える", "死"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 10,
        "notes": "ユーミンのデビュー作。死を正面から歌う歌謡史上の奇跡"
    },
    {
        "title": "卒業写真",
        "artist": "荒井由実",
        "year": 1975,
        "genre": "J-pop",
        "emotion_type": "青春/ノスタルジア/失われた時",
        "emotion_function": "共鳴",
        "consciousness_level": 8,
        "consciousness_notes": "「人混みに流されて変わってゆく私」という自己観察の鋭さ",
        "lyrics_keywords": ["卒業", "写真", "あの頃", "変わる"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "ユーミンの最高傑作の一つ。変化への正直な洞察"
    },
    {
        "title": "守ってあげたい",
        "artist": "松任谷由実",
        "year": 1981,
        "genre": "J-pop",
        "emotion_type": "保護/愛/母性",
        "emotion_function": "共鳴",
        "consciousness_level": 7,
        "consciousness_notes": "守る側の愛。ユーミンの女性的視点の独自性",
        "lyrics_keywords": ["守る", "あなた", "愛", "強く"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "ドラえもん映画テーマ。守護という愛の表現"
    },
    {
        "title": "DOLL",
        "artist": "岡田有希子",
        "year": 1986,
        "genre": "アイドル",
        "emotion_type": "人形/虚構/哀しみ",
        "emotion_function": "麻痺",
        "consciousness_level": 3,
        "consciousness_notes": "「人形」というアイドルの本質的な比喩。自身の悲劇の予感",
        "lyrics_keywords": ["人形", "DOLL", "笑顔", "虚ろ"],
        "cultural_impact": "大",
        "soul_freedom_score": 2,
        "truth_score": 6,
        "notes": "自殺した岡田有希子の曲。人形というアイドルの残酷な本質"
    },
    {
        "title": "くれない",
        "artist": "中森明菜",
        "year": 1984,
        "genre": "アイドル",
        "emotion_type": "怒り/要求/愛の不満",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "「くれない」という不満の率直な表現。受け身でないアイドル",
        "lyrics_keywords": ["くれない", "愛", "欲しい", "あなた"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "明菜の要求する女性像の表現"
    },
    {
        "title": "歌姫",
        "artist": "中西圭三",
        "year": 1992,
        "genre": "R&B/J-pop",
        "emotion_type": "歌う女性への崇拝/愛",
        "emotion_function": "昇華",
        "consciousness_level": 7,
        "consciousness_notes": "歌手という存在への崇拝。音楽の神聖さへの感謝",
        "lyrics_keywords": ["歌姫", "声", "美しい", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "R&B的感性が日本の歌謡曲に与えた影響"
    },
    {
        "title": "ロマンスの神様",
        "artist": "広瀬香美",
        "year": 1993,
        "genre": "J-pop",
        "emotion_type": "恋愛への懇願/願い",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "「ロマンスの神様」への懇願。外的な力への依存",
        "lyrics_keywords": ["ロマンス", "神様", "お願い", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "スキーリゾートブームの象徴。恋愛という宗教への祈り"
    },
    {
        "title": "好きよキャプテン",
        "artist": "トシちゃん（田原俊彦）",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "好き/告白/アイドル的恋愛",
        "emotion_function": "麻痺",
        "consciousness_level": 2,
        "consciousness_notes": "アイドル産業の典型的な恋愛消費パターン",
        "lyrics_keywords": ["好き", "キャプテン", "君", "恋"],
        "cultural_impact": "中",
        "soul_freedom_score": 2,
        "truth_score": 2,
        "notes": "アイドル恋愛歌謡の典型"
    },
    {
        "title": "真夏の少女",
        "artist": "郷ひろみ",
        "year": 1974,
        "genre": "アイドル/歌謡曲",
        "emotion_type": "夏/少女/憧れ",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "夏と少女というアイドル的組み合わせ",
        "lyrics_keywords": ["真夏", "少女", "砂浜", "恋"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "郷ひろみの人気絶頂期の代表曲"
    },
    {
        "title": "チェリー",
        "artist": "スピッツ",
        "year": 1996,
        "genre": "J-pop/バンド",
        "emotion_type": "純愛/永遠/チェリー",
        "emotion_function": "共鳴",
        "consciousness_level": 8,
        "consciousness_notes": "「愛してる」という言葉を超えた感情の比喩的表現",
        "lyrics_keywords": ["チェリー", "愛してる", "桜", "永遠"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "草野正宗の詩的才能の頂点。単純な言葉で深い感情を"
    },
    {
        "title": "君は天然色",
        "artist": "大滝詠一",
        "year": 1981,
        "genre": "シティポップ",
        "emotion_type": "色彩/失恋/記憶",
        "emotion_function": "昇華",
        "consciousness_level": 8,
        "consciousness_notes": "失われた恋を色彩として記憶する。感覚的な喪失の表現",
        "lyrics_keywords": ["天然色", "君", "色鉛筆", "夏"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 9,
        "notes": "松本隆・大滝詠一の最高傑作。日本シティポップの王冠"
    },
    {
        "title": "さらば青春の光",
        "artist": "森田公一とトップギャラン",
        "year": 1976,
        "genre": "歌謡曲",
        "emotion_type": "青春への惜別",
        "emotion_function": "昇華",
        "consciousness_level": 7,
        "consciousness_notes": "青春を「光」として別れを告げる。成長の痛みの表現",
        "lyrics_keywords": ["さらば", "青春", "光", "別れ"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "青春への惜別という普遍的テーマ"
    },
    {
        "title": "雨の慕情",
        "artist": "八代亜紀",
        "year": 1980,
        "genre": "演歌",
        "emotion_type": "雨/恋慕/孤独",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "雨という気象と恋慕の感情の融合",
        "lyrics_keywords": ["雨", "慕情", "傘", "一人"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "八代亜紀の雨シリーズ。レコード大賞受賞"
    },
    {
        "title": "もしもピアノが弾けたなら",
        "artist": "西田敏行",
        "year": 1981,
        "genre": "歌謡曲",
        "emotion_type": "願望/叶わぬ夢/愛",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "「もしも」という仮定法が示す感情の間接的表現",
        "lyrics_keywords": ["ピアノ", "弾けたなら", "もしも", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 7,
        "notes": "叶わない願望による感情の間接的表現の名作"
    },
    {
        "title": "天国にいちばん近い島",
        "artist": "原田知世",
        "year": 1984,
        "genre": "アイドル",
        "emotion_type": "遠い楽園/夢/少女",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "天国という理想への憧れ。少女的幻想",
        "lyrics_keywords": ["天国", "島", "遠い", "夢"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "映画タイアップ。原田知世の独特な透明感"
    },
    {
        "title": "麦わら帽子",
        "artist": "松田聖子",
        "year": 1982,
        "genre": "アイドル",
        "emotion_type": "夏/少女/純粋",
        "emotion_function": "共鳴",
        "consciousness_level": 4,
        "consciousness_notes": "夏と少女と帽子という記号的組み合わせ",
        "lyrics_keywords": ["麦わら", "帽子", "夏", "君"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "聖子の夏シリーズの一つ"
    },
    {
        "title": "セーラー服と機関銃",
        "artist": "薬師丸ひろ子",
        "year": 1981,
        "genre": "アイドル",
        "emotion_type": "少女/矛盾/対比",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "純粋さ（セーラー服）と暴力（機関銃）の矛盾する対比による解放感",
        "lyrics_keywords": ["セーラー服", "機関銃", "少女", "矛盾"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "映画タイアップの名曲。矛盾する要素の並置による詩的表現"
    },
    {
        "title": "探偵物語",
        "artist": "薬師丸ひろ子",
        "year": 1983,
        "genre": "アイドル",
        "emotion_type": "探偵/謎/大人への脱皮",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "探偵という役を通じた自己変容への欲求",
        "lyrics_keywords": ["探偵", "謎", "夜", "真実"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 5,
        "notes": "角川映画タイアップ。薬師丸の清楚な反抗"
    },
]

# ===== 4. 1990年代J-pop黄金期 (80曲) =====
JPOP_90S = [
    {
        "title": "負けないで",
        "artist": "ZARD",
        "year": 1993,
        "genre": "J-pop",
        "emotion_type": "励まし/頑張れ/前進",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "「負けないで」という直接的励ましは共感を呼ぶが感情の深化は促さない",
        "lyrics_keywords": ["負けないで", "もう少し", "最後まで", "走り続けて"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 6,
        "notes": "坂井泉水の声の力が歌詞の単純さを超える"
    },
    {
        "title": "揺れる想い",
        "artist": "ZARD",
        "year": 1993,
        "genre": "J-pop",
        "emotion_type": "揺れる感情/不安定な愛",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "感情の揺れという不安定さを正直に表現",
        "lyrics_keywords": ["揺れる", "想い", "心", "あなた"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ZARDの感情表現の正直さ"
    },
    {
        "title": "君がいない",
        "artist": "ZARD",
        "year": 1994,
        "genre": "J-pop",
        "emotion_type": "不在/寂しさ/恋しい",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "存在の不在による感情の空白",
        "lyrics_keywords": ["君", "いない", "寂しい", "恋しい"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ZARDの一貫した感情の誠実さ"
    },
    {
        "title": "DEPARTURES",
        "artist": "globe",
        "year": 1996,
        "genre": "J-pop/ダンス",
        "emotion_type": "旅立ち/別れ/希望",
        "emotion_function": "解放",
        "consciousness_level": 5,
        "consciousness_notes": "小室哲哉サウンドによる旅立ちの高揚感",
        "lyrics_keywords": ["旅立ち", "DEPARTURES", "君", "未来"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "globeの最大ヒット。小室哲哉ファミリーの頂点"
    },
    {
        "title": "FACE",
        "artist": "globe",
        "year": 1996,
        "genre": "J-pop/ダンス",
        "emotion_type": "顔/表面/内面",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "顔という表面と内面の乖離。小室哲哉の問題意識",
        "lyrics_keywords": ["FACE", "顔", "本当の", "表面"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "小室×KEIKOの化学反応"
    },
    {
        "title": "CAN YOU CELEBRATE?",
        "artist": "安室奈美恵",
        "year": 1997,
        "genre": "J-pop/ダンス",
        "emotion_type": "結婚/祝福/純愛",
        "emotion_function": "共鳴",
        "consciousness_level": 5,
        "consciousness_notes": "結婚という社会的契約への純粋な喜び",
        "lyrics_keywords": ["CELEBRATE", "結婚", "幸せ", "祝う"],
        "cultural_impact": "大",
        "soul_freedom_score": 5,
        "truth_score": 5,
        "notes": "自身の結婚発表と重なった運命的ヒット"
    },
    {
        "title": "SWEET 19 BLUES",
        "artist": "安室奈美恵",
        "year": 1996,
        "genre": "J-pop/R&B",
        "emotion_type": "19歳の憂鬱/成長痛",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "10代特有の感情の揺れを正直に描く",
        "lyrics_keywords": ["19", "BLUES", "憂鬱", "若さ"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "安室の実年齢と曲のテーマが一致した真正性"
    },
    {
        "title": "WOW WAR TONIGHT",
        "artist": "H Jungle with t",
        "year": 1995,
        "genre": "J-pop/ダンス",
        "emotion_type": "反抗/戦い/バブルの残滓",
        "emotion_function": "解放",
        "consciousness_level": 4,
        "consciousness_notes": "バブル後の表面的な反抗。「戦う」という言葉の空虚さ",
        "lyrics_keywords": ["WOW", "WAR", "TONIGHT", "戦う"],
        "cultural_impact": "大",
        "soul_freedom_score": 4,
        "truth_score": 4,
        "notes": "浜田雅功×小室哲哉。バブル後のエネルギーの発散"
    },
    {
        "title": "GET WILD",
        "artist": "TM NETWORK",
        "year": 1987,
        "genre": "J-pop/シンセポップ",
        "emotion_type": "都市/野生/解放",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "都市の中で野生を取り戻すという矛盾した欲求。シティへの反抗",
        "lyrics_keywords": ["GET", "WILD", "都市", "解放"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 6,
        "notes": "シティハンターED。都市と野生の二項対立"
    },
    {
        "title": "CITY HUNTER〜愛よ消えないで〜",
        "artist": "TM NETWORK",
        "year": 1987,
        "genre": "J-pop/シンセポップ",
        "emotion_type": "都市の愛/消えない",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "消えない愛への願い。都市の孤独の中の温かさ",
        "lyrics_keywords": ["CITY", "愛", "消えない"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "TM NETWORK初期の都市的ロマンティシズム"
    },
    {
        "title": "Hold On Me",
        "artist": "JUDY AND MARY",
        "year": 1995,
        "genre": "ロック/J-pop",
        "emotion_type": "支えてほしい/頼りたい",
        "emotion_function": "共鳴",
        "consciousness_level": 6,
        "consciousness_notes": "「私を持って」という正直な依存の要求",
        "lyrics_keywords": ["HOLD", "ME", "支え", "頼る"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ジュディマリの感情の正直さ"
    },
    {
        "title": "そばかす",
        "artist": "JUDY AND MARY",
        "year": 1996,
        "genre": "ロック/アニソン",
        "emotion_type": "自己肯定/個性/そばかす",
        "emotion_function": "解放",
        "consciousness_level": 7,
        "consciousness_notes": "欠点（そばかす）を個性として肯定する。ルパン三世との相乗効果",
        "lyrics_keywords": ["そばかす", "好き", "個性", "私"],
        "cultural_impact": "大",
        "soul_freedom_score": 7,
        "truth_score": 7,
        "notes": "ルパン三世タイアップ。欠点の肯定という解放的メッセージ"
    },
    {
        "title": "Over Drive",
        "artist": "JUDY AND MARY",
        "year": 1995,
        "genre": "ロック",
        "emotion_type": "スピード/解放/走る",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "スピードという身体的解放感",
        "lyrics_keywords": ["OVER", "DRIVE", "速い", "走る"],
        "cultural_impact": "大",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ジュディマリのエネルギーの爆発"
    },
    {
        "title": "ガレージはどこ？",
        "artist": "JUDY AND MARY",
        "year": 1993,
        "genre": "ロック",
        "emotion_type": "混乱/迷子/都市",
        "emotion_function": "解放",
        "consciousness_level": 6,
        "consciousness_notes": "都市での迷子という現代的不安の解放的表現",
        "lyrics_keywords": ["ガレージ", "どこ", "迷子", "都市"],
        "cultural_impact": "中",
        "soul_freedom_score": 6,
        "truth_score": 6,
        "notes": "ジュディマリの初期の個性"
    },
    {
        "title": "ロビンソン",
        "artist": "スピッツ",
        "year": 1995,
        "genre": "J-pop/バンド",
        "emotion_type": "純愛/普通/奇跡",
        "emotion_function": "昇華",
        "consciousness_level": 9,
        "consciousness_notes": "「誰も触れない二人だけの国」という孤島のような純粋な愛の世界",
        "lyrics_keywords": ["ロビンソン", "二人", "国", "奇跡"],
        "cultural_impact": "大",
        "soul_freedom_score": 9,
        "truth_score": 9,
        "notes": "草野正宗の詩世界の最高峰。愛の孤島という理想の表現"
    },
    {
        "title": "空も飛べるはず",
        "artist": "スピッツ",
        "year": 1994,
        "genre": "J-pop/バンド",
        "emotion_type": "可能性/愛/空",
        "emotion_function": "解放",
        "consciousness_level": 8,
        "consciousness_notes": "「空も飛べるはず」という愛の可能性への信頼",
        "lyrics_keywords": ["空", "飛べる", "はず", "愛"],
        "cultural_impact": "大",
        "soul_freedom_score": 8,
        "truth_score": 8,
        "notes": "スピッツの愛の超